package com.microsoft.cognitiveservices.speech.util;

/* JADX INFO: loaded from: C:\Users\abcsa\Downloads\Mouna\dex_temp\classes7.dex */
public enum SafeHandleType {
    UnInitialized,
    Event,
    Recognizer,
    SpeechConfig,
    AudioConfig,
    PropertyCollection,
    RecognitionResult,
    Connection,
    ConnectionMessage,
    ConnectionMessageEvent,
    AudioInputStream,
    AudioOutputStream,
    AudioStreamFormat,
    KeywordModel,
    User,
    Participant,
    Conversation,
    Meeting,
    DialogServiceConnector,
    TurnStatusReceivedEvent,
    ActivityReceivedEvent,
    AutoDetectSourceLanguageConfig,
    SourceLanguageConfig,
    SynthesisEvent,
    SynthesisRequest,
    SynthesisResult,
    VoiceInfo,
    AudioDataStream,
    Synthesizer,
    Grammar,
    TranslationSynthesis,
    ConversationTranslator,
    KeywordRecognizer,
    PronunciationAssessmentConfig,
    AudioProcessingOptions,
    SpeechRecognitionModel,
    SpeechTranslationModel,
    JSONVALUE,
    JSONBUILDER,
    EventLoggerCallback
}
